<a href="https://colab.research.google.com/github/ALRIER/BigData_2024/blob/main/TallerBigDataNataliaAranda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**En Python, crearemos un vector de 100 números aleatorios entre 1 y 100. En R, deberás hacer lo mismo pero con números aleatorios entre -50 y 50. Para ambos vectores, calcularemos la media, mediana, y desviación estándar. Luego, en cada lenguaje, identificaremos cuántos números son mayores que la media y cuántos son menores e imprimiremos estos resultados**

**Phyton**

In [ ]:
import random


In [ ]:
vector = random.choices(range(1, 101), k=100)
print(vector)


[43, 6, 56, 3, 46, 71, 8, 42, 65, 47, 39, 79, 98, 94, 46, 64, 38, 29, 12, 50, 69, 20, 66, 88, 96, 43, 51, 45, 89, 14, 73, 8, 75, 18, 22, 45, 26, 34, 1, 28, 76, 3, 95, 90, 3, 72, 64, 88, 81, 77, 70, 99, 20, 44, 68, 20, 73, 4, 8, 95, 23, 50, 27, 85, 63, 36, 78, 10, 73, 65, 16, 6, 75, 100, 43, 50, 1, 80, 46, 19, 70, 92, 84, 99, 80, 27, 2, 77, 55, 96, 1, 92, 79, 94, 9, 22, 60, 16, 62, 58]


In [ ]:
import random
import statistics



In [ ]:

media = statistics.mean(vector)
print("Media:", media)

mediana = statistics.median(vector)
print("Mediana:", mediana)

desviacion_estandar = statistics.stdev(vector)
print("Desviación Estándar:", desviacion_estandar)


Media: 51.18
Mediana: 50.5
Desviación Estándar: 30.83726592447796


In [ ]:
mayores_que_media = [num for num in vector if num > media]
cantidad_mayores = len(mayores_que_media)

menores_que_media = [num for num in vector if num < media]
cantidad_menores = len(menores_que_media)

print(f"Cantidad de números mayores que la media: {cantidad_mayores}")
print(f"Cantidad de números menores que la media: {cantidad_menores}")


Cantidad de números mayores que la media: 49
Cantidad de números menores que la media: 51


**R**

In [ ]:
!pip install rpy2


In [ ]:
%load_ext rpy2.ipython

In [ ]:
%%R
set.seed(123)
numeros_aleatorios <- sample(-50:50, 100, replace = TRUE)
print(numeros_aleatorios)


  [1] -20  28   0 -37  16  -9  -1  -8  50 -37 -26  39  40  18  40   6  41 -42
 [19]  42  48  21 -25 -44  -9 -42  32 -15  27  30  -8  25 -36 -19 -44 -42 -10
 [37]  23 -28 -24   9   2 -44   2 -24  45 -13  38 -17  42  18  21  25  12 -38
 [55]  31  46  40 -26 -13 -30  28 -10  -4  39   9  44 -35  43 -45  21  35  35
 [73] -12 -20  30  -1 -17 -47 -38  18 -26   1 -29  38 -19 -26  36 -16 -11 -21
 [91] -39 -20 -21  13  48 -37  42  45  20  16


In [ ]:
%%R

media <- mean(numeros_aleatorios)
mediana <- median(numeros_aleatorios)
desviacion_estandar <- sd(numeros_aleatorios)

print(paste("Media:", media))
print(paste("Mediana:", mediana))
print(paste("Desviación estándar:", desviacion_estandar))


[1] "Media: 1.93"
[1] "Mediana: -0.5"
[1] "Desviación estándar: 29.8268589555038"


In [ ]:
%%R
mayores_que_media <- sum(numeros_aleatorios > media)
print(paste("Números mayores que la media:", mayores_que_media))

menores_que_media <- sum(numeros_aleatorios < media)
print(paste("Números menores que la media:", menores_que_media))


[1] "Números mayores que la media: 48"
[1] "Números menores que la media: 52"


**2.Vamos a crear dos vectores de longitud desigual en R, uno representando temperaturas máximas y otro mínimas a lo largo de una semana, con algunos días faltantes en el vector de mínimas. Realizar una suma de ambos vectores para obtener un vector de temperaturas diarias, gestionando el reciclaje de vectores**

In [ ]:
%%R

temperaturas_max <- c(30, 32, 28, 29, 31, 33, 30)

temperaturas_min <- c(18, NA, 16, NA, 15, 19, NA)

temperaturas_diarias <- ifelse(is.na(temperaturas_min), temperaturas_max, temperaturas_max + temperaturas_min)

temperaturas_diarias



[1] 48 32 44 29 46 52 30


**3.1 Generar una matriz 5x5 en R y Python con números aleatorios. En R, reemplazar todos los valores por debajo de la mediana de la matriz por cero y todos los valores por encima de la mediana por uno, simulando una binarización. Luego vamos a utilizar cbind o rbind para agregar valores de ciudades de forma aleatoria a la matriz de R, después guardaremos la matriz en forma de dataframe para finalmente agregar nombres a las columnas del dataframe. (Asignaremos el nombre que querramos, lo importante es el resultado).**



In [ ]:
%%R
matriz <- matrix(runif(25), nrow=5, ncol=5)
print(matriz)


          [,1]      [,2]      [,3]       [,4]       [,5]
[1,] 0.3694889 0.6900071 0.5211357 0.43943154 0.84272932
[2,] 0.9842192 0.6192565 0.6598384 0.31170220 0.23116178
[3,] 0.1542023 0.8913941 0.8218055 0.40947495 0.23909996
[4,] 0.0910440 0.6729991 0.7862816 0.01046711 0.07669117
[5,] 0.1419069 0.7370777 0.9798219 0.18384952 0.24572368


In [ ]:
%%R
mediana <- median(matriz)

matriz_binarizada <- matriz
matriz_binarizada[matriz < mediana] <- 0
matriz_binarizada[matriz > mediana] <- 1

print("Matriz binarizada:")
print(matriz_binarizada)

[1] "Matriz binarizada:"
     [,1] [,2] [,3]      [,4] [,5]
[1,]    0    1    1 0.4394315    1
[2,]    1    1    1 0.0000000    0
[3,]    0    1    1 0.0000000    0
[4,]    0    1    1 0.0000000    0
[5,]    0    1    1 0.0000000    0


In [ ]:
%%R
ciudades <- c("Nueva York", "Tokio", "Londres", "París", "Sídney")

ciudades_aleatorias <- sample(ciudades, 5, replace = TRUE)

matriz_con_ciudades <- cbind(Ciudades = ciudades_aleatorias, matriz_binarizada)

print("Matriz con ciudades:")
print(matriz_con_ciudades)


[1] "Matriz con ciudades:"
     Ciudades                                        
[1,] "Londres"    "0" "1" "1" "0.439431536244228" "1"
[2,] "Nueva York" "1" "1" "1" "0"                 "0"
[3,] "Londres"    "0" "1" "1" "0"                 "0"
[4,] "Sídney"     "0" "1" "1" "0"                 "0"
[5,] "Tokio"      "0" "1" "1" "0"                 "0"


In [ ]:
%%R
df <- as.data.frame(matriz_con_ciudades)

print("Dataframe con ciudades:")
print(df)


[1] "Dataframe con ciudades:"
    Ciudades V2 V3 V4                V5 V6
1    Londres  0  1  1 0.439431536244228  1
2 Nueva York  1  1  1                 0  0
3    Londres  0  1  1                 0  0
4     Sídney  0  1  1                 0  0
5      Tokio  0  1  1                 0  0


In [ ]:
%%R
colnames(df) <- c("Ciudad", "A", "B", "C", "D", "E")

print("Dataframe con nombres de columnas:")
print(df)


[1] "Dataframe con nombres de columnas:"
      Ciudad A B C                 D E
1    Londres 0 1 1 0.439431536244228 1
2 Nueva York 1 1 1                 0 0
3    Londres 0 1 1                 0 0
4     Sídney 0 1 1                 0 0
5      Tokio 0 1 1                 0 0


**3.2 En python por otro lado, vamos a multiplicar nuestra matriz 5x5 por 2 y luego vamos a constuír un ciclo for que iteres sobre cada valor de la matriz y le agregue un valor de 1 a cada elemento de la misma. Finalmente, insertaremos un ciclo de control de flujo o condicional "if" que junto a un ciclo "for" recorra cada elemento de la matriz y verifique si el valor es > 10, entonces imprima "este número es mayor" y si el número es <= 10, entonces imprima, "Este número es menor".**

In [ ]:
import numpy as np
matriz = np.random.rand(5, 5)
matriz_multiplicada = matriz * 2
print("Matriz original:\n", matriz)
print("\nMatriz multiplicada por 2:\n", matriz_multiplicada)



Matriz original:
 [[0.1475278  0.94764525 0.06614258 0.30311198 0.18779986]
 [0.27142132 0.34640939 0.02901075 0.25272345 0.06011618]
 [0.77434149 0.4186195  0.19268034 0.77638976 0.83011883]
 [0.75431045 0.23616762 0.82000787 0.26380398 0.75520204]
 [0.08950874 0.5850998  0.12621949 0.40632161 0.55503719]]

Matriz multiplicada por 2:
 [[0.2950556  1.89529049 0.13228517 0.60622396 0.37559972]
 [0.54284264 0.69281878 0.05802151 0.50544691 0.12023237]
 [1.54868297 0.83723899 0.38536067 1.55277952 1.66023766]
 [1.5086209  0.47233524 1.64001574 0.52760796 1.51040407]
 [0.17901749 1.1701996  0.25243897 0.81264322 1.11007439]]


In [ ]:

for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        matriz[i, j] += 1
print("Matriz con 1 añadido a cada elemento:\n", matriz)


Matriz con 1 añadido a cada elemento:
 [[1.1475278  1.94764525 1.06614258 1.30311198 1.18779986]
 [1.27142132 1.34640939 1.02901075 1.25272345 1.06011618]
 [1.77434149 1.4186195  1.19268034 1.77638976 1.83011883]
 [1.75431045 1.23616762 1.82000787 1.26380398 1.75520204]
 [1.08950874 1.5850998  1.12621949 1.40632161 1.55503719]]


In [ ]:
for i in range(matriz.shape[0]):
    for j in range(matriz.shape[1]):
        if matriz[i, j] > 10:
            print(f"El valor {matriz[i, j]:.2f} en la posición ({i},{j}) es mayor a 10: Este número es mayor")
        else:
            print(f"El valor {matriz[i, j]:.2f} en la posición ({i},{j}) es menor o igual a 10: Este número es menor")


El valor 1.15 en la posición (0,0) es menor o igual a 10: Este número es menor
El valor 1.95 en la posición (0,1) es menor o igual a 10: Este número es menor
El valor 1.07 en la posición (0,2) es menor o igual a 10: Este número es menor
El valor 1.30 en la posición (0,3) es menor o igual a 10: Este número es menor
El valor 1.19 en la posición (0,4) es menor o igual a 10: Este número es menor
El valor 1.27 en la posición (1,0) es menor o igual a 10: Este número es menor
El valor 1.35 en la posición (1,1) es menor o igual a 10: Este número es menor
El valor 1.03 en la posición (1,2) es menor o igual a 10: Este número es menor
El valor 1.25 en la posición (1,3) es menor o igual a 10: Este número es menor
El valor 1.06 en la posición (1,4) es menor o igual a 10: Este número es menor
El valor 1.77 en la posición (2,0) es menor o igual a 10: Este número es menor
El valor 1.42 en la posición (2,1) es menor o igual a 10: Este número es menor
El valor 1.19 en la posición (2,2) es menor o igual 

4.Crear una lista en Python y un vector de listas en R que contengan números, cadenas, y otros elementos.

Crearemos también una función definida por ti que realice una operación matemática simple. Después, aplicar esta función a cada elemento numérico de la lista/vector y almacenar los resultados en una nueva estructura. Imprimir antes y después de aplicar la función. Ten en cuenta que cada lista y función, tanto en python como en R deben ser diferentes y realizar diferentes operaciones.

In [ ]:
mi_lista = [5, 10, 15, 20, 25, "Hola", True, None]

def sumar_diez(x):
    if isinstance(x, (int, float)):  # Verifica si es numérico
        return x + 10
    return x

print("Lista original:", mi_lista)

resultados = [sumar_diez(elemento) for elemento in mi_lista]

print("Lista después de aplicar la función:", resultados)



Lista original: [5, 10, 15, 20, 25, 'Hola', True, None]
Lista después de aplicar la función: [15, 20, 25, 30, 35, 'Hola', 11, None]


In [ ]:
%%R
mi_lista_r <- list(12, 24, 36, "Mundo", FALSE, 42, 58, "Texto adicional")

sumar_diez <- function(x) {
  if (is.numeric(x)) {
    return(x + 10)
  }
  return(x)
}


dividir_por_dos <- function(x) {
  if (is.numeric(x)) {
    return(x / 2)
  }
  return(x)
}


print("Lista original:")
print(mi_lista_r)


resultados_suma <- lapply(mi_lista_r, sumar_diez)

resultados_division <- lapply(mi_lista_r, dividir_por_dos)

print("Lista después de aplicar la función de división:")
print(resultados_division)



[1] "Lista original:"
[[1]]
[1] 12

[[2]]
[1] 24

[[3]]
[1] 36

[[4]]
[1] "Mundo"

[[5]]
[1] FALSE

[[6]]
[1] 42

[[7]]
[1] 58

[[8]]
[1] "Texto adicional"

[1] "Lista después de aplicar la función de división:"
[[1]]
[1] 6

[[2]]
[1] 12

[[3]]
[1] 18

[[4]]
[1] "Mundo"

[[5]]
[1] FALSE

[[6]]
[1] 21

[[7]]
[1] 29

[[8]]
[1] "Texto adicional"



5.Crear un diccionario en Python que simule una base de datos de usuarios, donde cada clave es un ID de usuario único y cada valor es otro diccionario con información como nombre, correo electrónico, y una lista de amigos (IDs). Intorduce al menos 100 valores en el diccionario.

Implementar 3 funciones para añadir un nuevo usuario, eliminar un usuario, y encontrar amigos en común entre dos usuarios. Imprimir resultados de estas operaciones.

Crea un ciclo "for" que itere sobre cada elemento del diccionario y extraiga un valor que tu selecciones, puede ser nombres, telefonos o otros valores, después guarda los valores en una nueva variable e imprime los resultados.

In [ ]:
!pip install faker


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 25.2 MB/s eta 0:00:00


In [ ]:
import random
from faker import Faker

# Inicializa Faker
fake = Faker()

# Definir número de usuarios
num_users = 100
import random
from faker import Faker

# Inicializa Faker
fake = Faker()

# Crear diccionario vacío para la base de datos de usuarios
users_db = {}

# Definir número de usuarios iniciales
num_users = 100

# Crear base de datos con 100 usuarios
for user_id in range(1, num_users + 1):
    name = fake.name()
    email = fake.email()

    # Generar lista de amigos (IDs de amigos)
    friends = random.sample(range(1, num_users + 1), random.randint(1, 10))
    if user_id in friends:
        friends.remove(user_id)

    # Añadir usuario al diccionario
    users_db[user_id] = {
        'name': name,
        'email': email,
        'friends': friends
    }

# Función para añadir un nuevo usuario
def add_user(user_id, name, email, friends):
    if user_id in users_db:
        print(f"El usuario con ID {user_id} ya existe.")
    else:
        users_db[user_id] = {
            'name': name,
            'email': email,
            'friends': friends
        }
        print(f"Usuario {name} agregado con ID {user_id}.")

# Función para eliminar un usuario
def remove_user(user_id):
    if user_id in users_db:
        del users_db[user_id]
        print(f"Usuario con ID {user_id} eliminado.")
        # Eliminar de las listas de amigos de otros usuarios
        for user in users_db.values():
            if user_id in user['friends']:
                user['friends'].remove(user_id)
    else:
        print(f"El usuario con ID {user_id} no existe.")

# Función para encontrar amigos en común entre dos usuarios
def common_friends(user_id_1, user_id_2):
    if user_id_1 in users_db and user_id_2 in users_db:
        friends_1 = set(users_db[user_id_1]['friends'])
        friends_2 = set(users_db[user_id_2]['friends'])
        common = friends_1.intersection(friends_2)
        return list(common)
    else:
        print("Uno o ambos usuarios no existen.")
        return []

# Añadir nuevo usuario
new_user_id = 101
add_user(new_user_id, fake.name(), fake.email(), [2, 5, 8])

# Eliminar un usuario
remove_user(10)

# Encontrar amigos en común entre dos usuarios
user_1_id = 1
user_2_id = 5
common = common_friends(user_1_id, user_2_id)
print(f"Amigos en común entre {user_1_id} y {user_2_id}: {common}")

# Ciclo "for" para extraer los nombres de los usuarios y guardarlos en una nueva lista
user_names = []
for user_id, user_data in users_db.items():
    user_names.append(user_data['name'])

# Imprimir los nombres de los usuarios
print("Nombres de los usuarios:")
print(user_names)


Usuario Nathan Sandoval agregado con ID 101.
Usuario con ID 10 eliminado.
Amigos en común entre 1 y 5: []
Nombres de los usuarios:
['Craig Graves', 'Jessica Sullivan', 'Michelle Torres', 'David Henderson', 'Mary Parsons', 'Scott Stafford', 'Jacqueline Mason', 'Bruce Marshall', 'Kenneth Bowen', 'Antonio Dalton', 'Veronica Herring', 'Maxwell Strickland', 'Natasha Horne', 'Andrew Adams', 'Jerry Torres', 'Chelsea Tate', 'Sandra Avery', 'Christopher Brown', 'Taylor Reed', 'Stephanie Murillo', 'Ariana Johnson', 'Ashley Conner', 'Michael Jones DVM', 'Pamela Douglas', 'Jerome Sims', 'Cynthia Hernandez', 'Sarah Schmitt', 'Leonard Skinner', 'Ashley Sanford', 'Robin Sanchez', 'David Lowe', 'Jason Hayes', 'Danielle Miller', 'Andrew Harrell', 'Charles Turner', 'Lawrence Hunter', 'Taylor Williams', 'Linda Williams', 'Katherine Lawson', 'Lori Andrews', 'Michael Keller', 'Chad Beard', 'Brandon Greer', 'Michelle Nelson', 'Clayton Shields', 'Justin Ray', 'Morgan Estrada', 'Tyrone Bernard', 'Christopher 

**6.Escribir un programa en Python y R que evalúe tres números (a, b, c) y determine si forman una secuencia creciente, decreciente, o son todos iguales. Utilizar operadores relacionales y lógicos para realizar las comparaciones y imprimir un mensaje con cada resultado. Si el conjunto de números es creciente, un mensaje, otro diferente si es decreciente y uno diferente si son iguales**

In [28]:
# Función para evaluar la secuencia de tres números
def evaluar_secuencia(a, b, c):
    # Verificar si la secuencia es creciente
    if a < b and b < c:
        print(f"La secuencia {a}, {b}, {c} es creciente.")

    # Verificar si la secuencia es decreciente
    elif a > b and b > c:
        print(f"La secuencia {a}, {b}, {c} es decreciente.")

    # Verificar si todos los números son iguales
    elif a == b and b == c:
        print(f"Los tres números {a}, {b}, {c} son iguales.")

    # Caso donde la secuencia no es ni creciente, ni decreciente, ni todos iguales
    else:
        print(f"La secuencia {a}, {b}, {c} no es ni creciente ni decreciente.")

# Ejemplo de uso
a = float(input("Introduce el valor de a: "))
b = float(input("Introduce el valor de b: "))
c = float(input("Introduce el valor de c: "))

# Llamada a la función y mostrar el resultado
evaluar_secuencia(a, b, c)


Introduce el valor de a: 4
Introduce el valor de b: 5
Introduce el valor de c: 7
La secuencia 4.0, 5.0, 7.0 es creciente.


In [30]:
# Función para evaluar la secuencia de tres números
def evaluar_secuencia(a, b, c):
    # Verificar si la secuencia es creciente
    if a < b and b < c:
        print(f"La secuencia {a}, {b}, {c} es creciente.")

    # Verificar si la secuencia es decreciente
    elif a > b and b > c:
        print(f"La secuencia {a}, {b}, {c} es decreciente.")

    # Verificar si todos los números son iguales
    elif a == b and b == c:
        print(f"Los tres números {a}, {b}, {c} son iguales.")

    # Caso donde la secuencia no es ni creciente, ni decreciente, ni todos iguales
    else:
        print(f"La secuencia {a}, {b}, {c} no es ni creciente ni decreciente.")

# Ejemplo de uso
a = float(input("Introduce el valor de a: "))
b = float(input("Introduce el valor de b: "))
c = float(input("Introduce el valor de c: "))

# Llamada a la función y mostrar el resultado
evaluar_secuencia(a, b, c)



Introduce el valor de a: 50
Introduce el valor de b: 34
Introduce el valor de c: 21
La secuencia 50.0, 34.0, 21.0 es decreciente.


In [29]:
%%R
# Función para evaluar la secuencia de tres números
evaluar_secuencia <- function(a, b, c) {
  # Verificar si la secuencia es creciente
  if (a < b & b < c) {
    print(paste("La secuencia", a, b, c, "es creciente."))
  }
  # Verificar si la secuencia es decreciente
  else if (a > b & b > c) {
    print(paste("La secuencia", a, b, c, "es decreciente."))
  }
  # Verificar si todos los números son iguales
  else if (a == b & b == c) {
    print(paste("Los tres números", a, b, c, "son iguales."))
  }
  # Caso donde no es ni creciente, ni decreciente
  else {
    print(paste("La secuencia", a, b, c, "no es ni creciente ni decreciente."))
  }
}

# Ejemplo de uso
a <- as.numeric(readline(prompt = "Introduce el valor de a: "))
b <- as.numeric(readline(prompt = "Introduce el valor de b: "))
c <- as.numeric(readline(prompt = "Introduce el valor de c: "))

# Llamada a la función y mostrar el resultado
evaluar_secuencia(a, b, c)



Introduce el valor de a: 6
Introduce el valor de b: 23
Introduce el valor de c: 87
[1] "La secuencia 6 23 87 es creciente."


In [31]:
%%R
# Función para evaluar la secuencia de tres números
evaluar_secuencia <- function(a, b, c) {
  # Verificar si la secuencia es creciente
  if (a < b & b < c) {
    print(paste("La secuencia", a, b, c, "es creciente."))
  }
  # Verificar si la secuencia es decreciente
  else if (a > b & b > c) {
    print(paste("La secuencia", a, b, c, "es decreciente."))
  }
  # Verificar si todos los números son iguales
  else if (a == b & b == c) {
    print(paste("Los tres números", a, b, c, "son iguales."))
  }
  # Caso donde no es ni creciente, ni decreciente
  else {
    print(paste("La secuencia", a, b, c, "no es ni creciente ni decreciente."))
  }
}

# Ejemplo de uso
a <- as.numeric(readline(prompt = "Introduce el valor de a: "))
b <- as.numeric(readline(prompt = "Introduce el valor de b: "))
c <- as.numeric(readline(prompt = "Introduce el valor de c: "))

# Llamada a la función y mostrar el resultado
evaluar_secuencia(a, b, c)


Introduce el valor de a: 54
Introduce el valor de b: 32
Introduce el valor de c: 2
[1] "La secuencia 54 32 2 es decreciente."


7.Implementar un script en Python y R que simule el lanzamiento de un dado de 6 caras 100 veces. Almacenar los resultados en una estructura de datos y luego calcular la frecuencia de cada resultado. Utilizar bucles for para iterar sobre las simulaciones y estructuras de control de flujo para gestionar el conteo. Imprimir un resumen de las frecuencias de cada cara del dado.

Finalmente, desglosa y entiende el código desarrollado para ser capaz de explicar paso a paso lo que se ha hecho y qué hace cada parte de tu respuesta.

In [32]:
import random
from collections import Counter

# Lista para almacenar los resultados de los lanzamientos
resultados = []

# Simulación de 100 lanzamientos de un dado de 6 caras
for i in range(100):
    resultado = random.randint(1, 6)
    resultados.append(resultado)

# Mostrar los resultados
print(resultados)

# Analizar la frecuencia de los resultados
frecuencias = Counter(resultados)
print(frecuencias)


[3, 6, 3, 6, 6, 2, 3, 3, 2, 5, 2, 3, 4, 3, 5, 5, 6, 6, 4, 2, 1, 2, 1, 4, 6, 3, 5, 4, 2, 3, 5, 1, 5, 6, 4, 1, 1, 2, 3, 3, 5, 1, 4, 3, 1, 2, 4, 5, 1, 4, 3, 1, 3, 1, 3, 3, 2, 6, 2, 4, 4, 4, 2, 6, 3, 6, 4, 3, 4, 1, 6, 4, 3, 3, 1, 4, 1, 3, 2, 4, 1, 6, 6, 5, 6, 5, 5, 4, 4, 5, 4, 2, 5, 2, 3, 1, 4, 3, 6, 3]
Counter({3: 23, 4: 20, 6: 15, 1: 15, 2: 14, 5: 13})


In [33]:
import random

# Inicializar lista para resultados y diccionario para frecuencias
resultados = []
frecuencia = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0}

# Simulación de 100 lanzamientos de un dado de 6 caras
for i in range(100):
    resultado = random.randint(1, 6)
    resultados.append(resultado)

# Calcular la frecuencia de cada número
for resultado in resultados:
    if resultado in frecuencia:
        frecuencia[resultado] += 1

# Imprimir el resumen de frecuencias
print("Frecuencia de cada cara del dado:")
for numero, conteo in frecuencia.items():
    print(f"Cara {numero}: {conteo} veces")


Frecuencia de cada cara del dado:
Cara 1: 17 veces
Cara 2: 17 veces
Cara 3: 15 veces
Cara 4: 20 veces
Cara 5: 17 veces
Cara 6: 14 veces


In [36]:
%%R
# Inicializar una lista vacía para almacenar los resultados
resultados <- numeric(100)

# Inicializar un vector para almacenar la frecuencia de cada cara del dado
frecuencia <- numeric(6)

# Simulación de 100 lanzamientos de un dado de 6 caras
for (i in 1:100) {
    # Generar un número aleatorio entre 1 y 6 (simulando un lanzamiento de dado)
    lanzamiento <- sample(1:6, 1)

    # Almacenar el resultado del lanzamiento en el vector 'resultados'
    resultados[i] <- lanzamiento
}

# Contar la frecuencia de cada cara del dado (del 1 al 6)
for (j in 1:6) {
    # Contar cuántas veces aparece el número 'j' en los resultados
    frecuencia[j] <- sum(resultados == j)
}

# Imprimir el resumen de frecuencias
cat("Frecuencia de cada cara del dado:\n")
for (j in 1:6) {
    cat(paste("Cara", j, ":", frecuencia[j], "veces\n"))
}



Frecuencia de cada cara del dado:
Cara 1 : 22 veces
Cara 2 : 21 veces
Cara 3 : 11 veces
Cara 4 : 12 veces
Cara 5 : 25 veces
Cara 6 : 9 veces
